# config.yaml
csv:
  file_path: "data/new_office_supplies_dataset.csv"
  encoding: "utf-8"
  delimiter: ","
  columns:
    leaf: "Leaf"
    category_id: "ID"
    path: "Path"
    level: "Level"
    brand: "Brand"
    colour: "Colour"
    material: "Material"
    size_group: "Size group"
    author: "Author"
    title: "Title"
    isbn: "ISBN"
    package_size: "All shippable"
    conditions:
      - "New with tags"
      - "New without tags"
      - "Very good"
      - "Good"
      - "Satisfactory"
      - "Not fully functional"

output:
  kotlin_file: "output/leaf_category_models.kt"

mappings:
  conditions:
    "New with tags": "VintedConditionTypes.NEW_WITH_TAGS.id"
    "New without tags": "VintedConditionTypes.NEW_WITHOUT_TAGS.id"
    "Very good": "VintedConditionTypes.VERY_GOOD.id"
    "Good": "VintedConditionTypes.GOOD.id"
    "Satisfactory": "VintedConditionTypes.SATISFACTORY.id"
    "Not fully functional": "VintedConditionTypes.NOT_FULLY_FUNCTIONAL.id"

  package_sizes:
    "All shippable":
      - "VintedPackageTypes.SMALL.id"
      - "VintedPackageTypes.MEDIUM.id"
      - "VintedPackageTypes.LARGE.id"
    "Light bulky":
      - "VintedPackageTypes.BULKY_SMALL.id"
      - "VintedPackageTypes.BULKY_MEDIUM.id"
      - "VintedPackageTypes.BULKY_LARGE.id"
      - "VintedPackageTypes.BULKY_X_LARGE.id"
    "Heavy":
      - "VintedPackageTypes.HEAVY_SMALL.id"
      - "VintedPackageTypes.HEAVY_MEDIUM.id"
      - "VintedPackageTypes.HEAVY_LARGE.id"
    "Heavy bulky":
      - "VintedPackageTypes.HEAVY_BULKY_SMALL.id"
      - "VintedPackageTypes.HEAVY_BULKY_MEDIUM.id"
      - "VintedPackageTypes.HEAVY_BULKY_LARGE.id"

  field_types:
    "Upload Form + Filters":
      brand: { upload_form: true, filter: true }
      colour: { upload_form: true, filter: true }
      material: { upload_form: true, filter: true }
      size_group: { upload_form: true, filter: true }
    "Upload Form Only":
      author: { upload_form: true, filter: false }
      title: { upload_form: true, filter: false }
      isbn: { upload_form: true, filter: false }
    "Filters Only":
      # Add any filters-only fields here if they exist in the future